name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: 1.21

    - name: Build
      run: go build -v .
    
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5.1.1

  govulncheck:
    name: go vuln check
    runs-on: ubuntu-latest
    steps:
    - id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: 1.22.4
        go-package: ./...
